name: ToDo List Tasks
description: "Create a list of ToDo tasks (Note: Use the "Sub-Task" template if you are working on a task from a list)."
title: "[ToDo List]: <TITLE>"
labels: "ToDo"
body:
  - type: input
    id: task_description
    attributes:
      label: Description
      description: Provide a description for the ToDo tasks below.
      placeholder: e.g. Add Instance Methods to TensorFlow Frontend.
    validations:
      required: true
  - type: textarea
    id: task_list
    attributes:
      label: Task List
      description: Make a checkbox for each task.
      value: |
        - [ ] task 1
        - [ ] task 2
    validations:
      required: true
