name: determine-test-coverage
on:
  workflow_dispatch:
permissions:
  actions: read
jobs:
   job_1:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout Ivy 🛎
         uses: actions/checkout@v2
         with:
           path: ivy
           persist-credentials: false
           submodules: "recursive"
           fetch-depth: 150

       - name: Determine Test Coverage
         run: |
           pip install pydriller tqdm
           cd ivy
           python determine_test_coverage.py 0
           cd ..
           mkdir tests
           cp ivy/tests.pbz2 tests/

       - name: Push Mapping
         uses: cpina/github-action-push-to-another-repository@main
         env:
           SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
         with:
           source-directory: tests/
           destination-github-username: 'unifyai'
           destination-repository-name: 'Mapping'
           user-email: rashul.chutani@gmail.com
           commit-message: Update Mapping
           target-branch: master

   job_2:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout Ivy 🛎
         uses: actions/checkout@v2
         with:
           path: ivy
           persist-credentials: false
           submodules: "recursive"
           fetch-depth: 150

       - name: Determine Test Coverage
         run: |
           pip install pydriller tqdm
           cd ivy
           python determine_test_coverage.py 1
           cd ..
           mkdir tests
           cp ivy/tests.pbz2 tests/

       - name: Push Mapping
         uses: cpina/github-action-push-to-another-repository@main
         env:
           SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY2 }}
         with:
           source-directory: tests/
           destination-github-username: 'unifyai'
           destination-repository-name: 'Mapping_2'
           user-email: rashul.chutani@gmail.com
           commit-message: Update Mapping
           target-branch: master

   job_3:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout Ivy 🛎
         uses: actions/checkout@v2
         with:
           path: ivy
           persist-credentials: false
           submodules: "recursive"
           fetch-depth: 150

       - name: Determine Test Coverage
         run: |
           pip install pydriller tqdm
           cd ivy
           python determine_test_coverage.py 2
           cd ..
           mkdir tests
           cp ivy/tests.pbz2 tests/

       - name: Push Mapping
         uses: cpina/github-action-push-to-another-repository@main
         env:
           SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY3 }}
         with:
           source-directory: tests/
           destination-github-username: 'unifyai'
           destination-repository-name: 'Mapping_3'
           user-email: rashul.chutani@gmail.com
           commit-message: Update Mapping
           target-branch: master

   job_4:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout Ivy 🛎
         uses: actions/checkout@v2
         with:
           path: ivy
           persist-credentials: false
           submodules: "recursive"
           fetch-depth: 150

       - name: Determine Test Coverage
         run: |
           pip install pydriller tqdm
           cd ivy
           python determine_test_coverage.py 3
           cd ..
           mkdir tests
           cp ivy/tests.pbz2 tests/

       - name: Push Mapping
         uses: cpina/github-action-push-to-another-repository@main
         env:
           SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY4 }}
         with:
           source-directory: tests/
           destination-github-username: 'unifyai'
           destination-repository-name: 'Mapping_4'
           user-email: rashul.chutani@gmail.com
           commit-message: Update Mapping
           target-branch: master
