name: determine-test-coverage
on:
  workflow_dispatch:
permissions:
  actions: read
jobs:
   run_tests:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout Ivy 🛎
         uses: actions/checkout@v2
         with:
           path: ivy
           persist-credentials: false
           submodules: "recursive"

       - name: Determine Test Coverage
         run: |
           sudo apt-get install -y python3 python3-pip python3-tk
           pip3 install --upgrade pip
           pip3 install setuptools==58.5.3
           pip3 install torch==1.11.0+cpu -f https://download.pytorch.org/whl/torch_stable.html
           pip3 install -r ivy/requirements/requirements.txt
           pip3 install -r ivy/requirements/optional.txt
           pip3 install pydriller tqdm coverage
           git clone https://github.com/unifyai/Mapping.git
           cp Mapping/tests.pkl ivy/
           cd ivy
           python3 determine_test_coverage.py
           cd ..
           mkdir tests
           cp ivy/tests.pkl tests/

       - name: Push Mapping
         uses: cpina/github-action-push-to-another-repository@main
         env:
           SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
         with:
           source-directory: tests/
           destination-github-username: 'unifyai'
           destination-repository-name: 'Mapping'
           user-email: rashul.chutani@gmail.com
           commit-message: Update Mapping
           target-branch: master