name: determine-test-coverage
on:
  workflow_dispatch:
permissions:
  actions: read
jobs:
   run_tests:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout Ivy 🛎
         uses: actions/checkout@v2
         with:
           path: ivy
           persist-credentials: false
           submodules: "recursive"

       - name: Determine Test Coverage
         run: |
           pip install pydriller tqdm coverage
           cd ivy
           python determine_test_coverage.py
           cd ..
           mkdir tests
           cp ivy/tests.pkl tests/

       - name: Push Mapping
         uses: cpina/github-action-push-to-another-repository@main
         env:
           SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
         with:
           source-directory: tests/
           destination-github-username: 'unifyai'
           destination-repository-name: 'Mapping'
           user-email: rashul.chutani@gmail.com
           commit-message: Testing
           target-branch: master