name: Build DockerfileCopsim

on:
  push:
    branches: [ "master" ]
  pull_request:
    types: [labeled, opened, reopened, edited]
    branches: [ "master" ]

jobs:

  build:
    if: ${{ github.event.label.name!='Function Reformatting' }}
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    - name: Build DockerfileCopsim
      run: docker build . --file DockerfileCopsim --tag unifyai/ivy:copsim$(date +%s)
