name: intelligent-tests
on:
  workflow_dispatch:
  push:
permissions:
  actions: read
jobs:
   run_tests:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout Ivy 🛎
         uses: actions/checkout@v2
         with:
           path: ivy
           persist-credentials: false
           submodules: "recursive"
           fetch-depth: 100

       - name: Determine and Run Tests
         run: |
           git clone https://github.com/unifyai/Mapping.git
           pip install pydriller
           cp Mapping/tests.pkl ivy/
           cd ivy
           python determine_tests.py

#       - name: Run Functional-Core Tests
#         id: tests
#         if: steps.check_file_changed.outputs.changed == 'True' || steps.check_file_changed.conclusion == 'skipped'
#         run: |
#           cd ivy
#           ./run_tests_CLI/test_ivy_core.sh ${{ matrix.backends }} test_${{ matrix.submodules }} ${{ secrets.REDIS_CONNECTION_URL }} ${{ secrets.REDIS_PASSWORD}}
#         continue-on-error: true
