name: 'Close stale PRs'
on:
  schedule:
    - cron: '30 1 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v5
        with:
          stale-pr-message: 'This PR is stale because it has been open 7 days with no activity. Remove stale label or comment or this will be closed in 7 days.'
          close-pr-message: 'This PR was closed because it has been stalled for 7 days with no activity. You could reopen the PR if you still would like to work on it, and please make sure to have some kind of activity in your PR , as leaving it stalled for too long would result in the PR being closed.'
          exempt-pr-labels: "Next Release, Permanent, Extension, Sub Task"
          days-before-pr-stale: 7
          days-before-pr-close: 7
