name: test-frontend-numpy
on: [push, pull_request, workflow_dispatch]
jobs:
  run-nightly-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️Ivy
        uses: actions/checkout@v2
        with:
          path: ivy
          persist-credentials: false
          submodules: "recursive"

      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: test-frontend-numpy.yml
          workflow_conclusion: completed
          name: hypothesis_frontend_numpy_zip
          path: |
            ivy/.hypothesis/

      - name: Unzip Hypothesis Examples
        run: |
          cd ivy/.hypothesis
          unzip examples.zip
          rm examples.zip

      - name: Run Frontend Tests
        id: tests
        run: |
          cd ivy
          docker run --rm -v `pwd`:/ivy -v `pwd`/.hypothesis:/.hypothesis unifyai/ivy:latest python3 -m pytest --backend numpy ivy/ivy_tests/test_ivy/test_frontends/test_numpy
        continue-on-error: true

      - name: Zip Hypothesis Examples
        run: |
          cd ivy/.hypothesis
          zip -r examples.zip examples

      - name: Upload hypothesis
        uses: actions/upload-artifact@v3
        with:
          name: hypothesis_frontend_numpy_zip
          path: |
            ivy/.hypothesis/examples.zip

      - name: Check on failures
        if: steps.tests.outcome != 'success'
        run: exit 1
