name: test-array-api
on:
  push:
  pull_request:
    types: [labeled, opened, synchronize, reopened, review_requested]
  workflow_dispatch:

jobs:
  run-array-api-tests:
    if: ${{(github.event_name == 'push') || contains(github.event.pull_request.labels.*.name, 'Array API')}}
    strategy:
      matrix:
        backends: [numpy, torch, jax, tensorflow]
        submodules: [test_array_object, test_constants, test_creation_functions, test_data_type_functions,
                    test_linalg, test_manipulation_functions, test_operators_and_elementwise_functions,
                    test_searching_functions, test_set_functions, test_signatures, test_sorting_functions,
                    test_special_cases, test_statistical_functions, test_type_promotion, test_utility_functions,
                     meta/test_array_helpers, meta/test_broadcasting, meta/test_equality_mapping,
                     meta/test_hypothesis_helpers, meta/test_partial_adopters, meta/test_pytest_helpers,
                     meta/test_signatures, meta/test_special_cases, meta/test_utils]
    continue-on-error: true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️Ivy
        uses: actions/checkout@v2
        with:
          path: ivy
          persist-credentials: false
          submodules: 'recursive'

      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: test-array-api.yml
          workflow_conclusion: completed
          name: 'hypothesis_${{ matrix.backends }}_${{ matrix.submodules }}_zip'
          path: |
            ivy/.hypothesis/
        continue-on-error: true

      - name: Unzip Hypothesis Examples
        id: unzip
        run: |
          cd ivy/.hypothesis
          unzip examples.zip
          rm examples.zip
        continue-on-error: true

      - name: Create Hypothesis Directory
        if: steps.unzip.outcome != 'success'
        run: |
          cd ivy
          mkdir -p .hypothesis
          cd .hypothesis
          mkdir -p examples
        continue-on-error: true

      - name: Run Array Api Tests
        id: tests
        run: |
          cd ivy
          ./test_array_api.sh ${{matrix.backends}} ${{matrix.submodules}}
        continue-on-error: true

      - name: Zip Hypothesis Examples
        run: |
          cd ivy/.hypothesis
          zip -r examples.zip examples
        continue-on-error: true

      - name: Upload hypothesis
        uses: actions/upload-artifact@v3
        with:
          name: 'hypothesis_${{ matrix.backends }}_${{ matrix.submodules }}_zip'
          path: |
            ivy/.hypothesis/examples.zip
        continue-on-error: true

      - name: Check on failures
        if: steps.tests.outcome != 'success'
        run: exit 1
