name: test-frontend-tensorflow-push
on: push
jobs:
  run-nightly-tests:
    strategy:
      matrix:
        backends: [numpy, torch, jax, tensorflow ]
        submodules: [activations, layers, math, metrics, nest, nn, quantization, random, raw_ops,
                    regularizers, sets, signal, sparse, tensor]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️Ivy
        uses: actions/checkout@v2
        with:
          path: ivy
          persist-credentials: false
          submodules: "recursive"

      - name: Run Frontend Tests
        id: tests
        run: |
          cd ivy
          ./run_tests_CLI/test_tensorflow_frontend.sh ${{ matrix.backends }} test_${{ matrix.submodules }} ${{ secrets.REDIS_CONNECTION_URL }} ${{ secrets.REDIS_PASSWORD}}
        continue-on-error: true

      - name: Install Mongo Python Client
        uses: BSFishy/pip-action@v1
        with:
            packages: |
              pymongo[srv]

      - name: Update Database
        env:
            MONGODB_PASSWORD: ${{ secrets.MONGODB_PASSWORD }}
        run: |
            cd ivy/automation_tools/dashboard_automation/
            python3 update_db.py "$MONGODB_PASSWORD" ${{ github.workflow }} "${{ matrix.backends }}-${{ matrix.submodules }}" ${{ steps.tests.outcome }} ${{ github.run_id }}
        continue-on-error: true

      - name: Check on failures
        if: steps.tests.outcome != 'success'
        run: exit 1
