name: test-nn-ivy
on:
  push:
  pull_request:
    types: [labeled, opened, synchronize, reopened, review_requested]
permissions:
  actions: read
jobs:
   run-nightly-tests:
     if: ${{(github.event_name == 'push') || contains(github.event.pull_request.labels.*.name, 'Ivy Functional API')}}
     strategy:
       matrix:
         backends :  [numpy, torch, jax, tensorflow]
         submodules: [activations, layers, losses, norms]
     continue-on-error: true
     runs-on: ubuntu-latest
     steps:
       - name: Checkout 🛎️Ivy
         uses: actions/checkout@v2
         with:
           path: ivy
           persist-credentials: false
           submodules: "recursive"
           fetch-depth: 2

       - name: Check Files Changed
         shell: pwsh
         id: check_file_changed
         run: |
           cd ivy
           $diff = git diff --name-only HEAD^ HEAD
           $SourceDiff = $diff | Where-Object { `
             $_ -match 'ivy_tests/test_ivy/test_functional/test_nn/test_${{ matrix.submodules }}.py' `
             -or $_ -match 'ivy_tests/test_ivy/helpers.py' `
             -or $_ -match 'ivy/array/${{ matrix.submodules }}.py' `
             -or $_ -match 'ivy/container/${{ matrix.submodules }}.py' `
             -or $_ -match 'ivy/functional/backends/${{ matrix.backends }}/${{ matrix.submodules }}.py' `
             -or $_ -match 'ivy/functional/ivy/${{ matrix.submodules }}.py' `
           }
           $HasDiff = $SourceDiff.Length -gt 0
           $a = Get-Random -Maximum 10
           $HasDiff = $HasDiff -or ($a -eq 1)
           Write-Host "::set-output name=changed::$HasDiff"

       - name: Download artifact
         uses: dawidd6/action-download-artifact@v2
         if: steps.check_file_changed.outputs.changed == 'True'
         with:
           github_token: ${{secrets.GITHUB_TOKEN}}
           workflow: test-ivy-nn.yml
           workflow_conclusion: ""
           search_artifacts: true
           name: hypothesis_${{ matrix.backends }}_test_${{ matrix.submodules }}_zip
           path: |
             ivy/.hypothesis/
         continue-on-error: true

       - name: Unzip Hypothesis Examples
         id: unzip
         if: steps.check_file_changed.outputs.changed == 'True'
         run: |
           cd ivy/.hypothesis
           unzip examples.zip
           rm examples.zip
         continue-on-error: true

       - name: Create Hypothesis Directory
         if: steps.check_file_changed.outputs.changed == 'True' && steps.unzip.outcome != 'success'
         run: |
           cd ivy
           mkdir -p .hypothesis
           cd .hypothesis
           mkdir -p examples
         continue-on-error: true

       - name: Run Functional-NN Tests
         id: tests
         if: steps.check_file_changed.outputs.changed == 'True'
         run: |
           cd ivy
           ./run_tests_CLI/test_ivy_nn.sh ${{ matrix.backends }} test_${{ matrix.submodules }}
         continue-on-error: true

       - name: Zip Hypothesis Examples
         if: steps.check_file_changed.outputs.changed == 'True'
         run: |
           cd ivy/.hypothesis
           zip -r examples.zip examples
         continue-on-error: true

       - name: Upload hypothesis
         uses: actions/upload-artifact@v3
         if: steps.check_file_changed.outputs.changed == 'True'
         with:
           name: hypothesis_${{ matrix.backends }}_test_${{ matrix.submodules }}_zip
           path: |
             ivy/.hypothesis/examples.zip
         continue-on-error: true

       - name: Check on failures
         if: steps.check_file_changed.outputs.changed == 'True' && steps.tests.outcome != 'success'
         run: exit 1
