name: test-array-api-torch
on:
  push:
  pull_request:
    types: [labeled, review_requested]
  workflow_dispatch:

jobs:
  run-torch-array-api-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️Ivy
        uses: actions/checkout@v2
        with:
          path: ivy
          persist-credentials: false
          submodules: 'recursive'

      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: test-array-api-torch.yml
          workflow_conclusion: completed
          name: hypothesis_torch_zip
          path: |
            ivy/.hypothesis/
        continue-on-error: true

      - name: Unzip Hypothesis Examples
        id: unzip
        run: |
          cd ivy/.hypothesis
          unzip examples.zip
          rm examples.zip
        continue-on-error: true

      - name: Create Hypothesis Directory
        if: steps.unzip.outcome != 'success'
        run: |
          cd ivy
          mkdir -p .hypothesis
          cd .hypothesis
          mkdir -p examples
        continue-on-error: true

      - name: Run Frontend Tests
        id: tests
        run: |
          cd ivy
          ./test_array_api.sh torch
        continue-on-error: true

      - name: Zip Hypothesis Examples
        run: |
          cd ivy/.hypothesis
          zip -r examples.zip examples
        continue-on-error: true

      - name: Upload hypothesis
        uses: actions/upload-artifact@v3
        with:
          name: hypothesis_torch_zip
          path: |
            ivy/.hypothesis/examples.zip
        continue-on-error: true

      - name: Check on failures
        if: steps.tests.outcome != 'success'
        run: exit 1
