name: test-nn-ivy-cron
on:
  schedule:
    - cron: '30 * * * *'
permissions:
  actions: read
jobs:
   run-nightly-tests:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout 🛎️Ivy
         uses: actions/checkout@v2
         with:
           path: ivy
           persist-credentials: false
           submodules: "recursive"

       - name: Run Functional-NN Tests
         id: tests
         shell: pwsh
         run: |
           cd ivy
           python run_tests_CLI/run_ivy_nn_test.py ${{ github.run_number }}
           Write-Host "::set-output name=fw_submod::$(cat fwsubmod.txt)"
           ./run_tests_CLI/test_ivy_nn.sh $(cat backend.txt) $(cat submodule.txt) ${{ secrets.REDIS_CONNECTION_URL }} ${{ secrets.REDIS_PASSWORD}}
         continue-on-error: true

       - name: Install Mongo Python Client
         uses: BSFishy/pip-action@v1
         with:
             packages: |
               pymongo[srv]

       - name: Update Database
         env:
             MONGODB_PASSWORD: ${{ secrets.MONGODB_PASSWORD }}
         run: |
           cd ivy/automation_tools/dashboard_automation/
           python3 update_db.py "$MONGODB_PASSWORD" "test-nn-ivy" ${{ steps.tests.outputs.fw_submod}} ${{ steps.tests.outcome }} ${{ github.run_id }}
         continue-on-error: true

       - name: Check on failures
         if: steps.tests.outcome != 'success'
         run: exit 1
