name: test-core-ivy-manual
on:
  workflow_dispatch:

permissions:
  actions: read
jobs:
   run-nightly-tests:
     strategy:
       matrix:
         backends :  [numpy, torch, jax, tensorflow]
         submodules: [test_creation, test_device, test_dtype, test_elementwise, test_general, test_gradients, test_linalg,
                     test_manipulation, test_meta, test_nest, test_random, test_searching, test_set, test_sorting, test_statistical,
                     test_utility]
     continue-on-error: true
     runs-on: ubuntu-latest
     steps:
       - name: Checkout 🛎️Ivy
         uses: actions/checkout@v2
         with:
           path: ivy
           persist-credentials: false
           submodules: "recursive"

       - name: Run Functional-Core Tests
         id: tests
         run: |
           cd ivy
           ./run_tests_CLI/test_ivy_core.sh ${{ matrix.backends }} ${{ matrix.submodules }} ${{ secrets.REDIS_CONNECTION_URL }} ${{ secrets.REDIS_PASSWORD}}
         continue-on-error: true

       - name: Check on failures
         if: steps.tests.outcome != 'success'
         run: exit 1