name: test-st-modules-tensorflow
on:
  push:
  pull_request:
    types: [labeled, review_requested]
jobs:
  run-nightly-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️Ivy
        uses: actions/checkout@v2
        with:
          path: ivy
          persist-credentials: false
          submodules: "recursive"



      - name: Run Conversion Tests
        run: |
          cd ivy
          mkdir -p .hypothesis
          docker run --rm -v `pwd`:/ivy -v `pwd`/.hypothesis:/.hypothesis unifyai/ivy:latest python3 -m pytest --backend tensorflow ivy/ivy_tests/test_ivy/test_stateful/test_modules.py

      - name: Zip Hypothesis Examples
        run: |
          cd ivy/.hypothesis
          zip -r examples.zip examples

      - name: Upload hypothesis
        uses: actions/upload-artifact@v3
        with:
          name: hypothesis_fn_gradients_tf_zip
          path: |
            ivy/.hypothesis/examples.zip

      - name: Check on failures
        if: steps.tests.outcome != 'success'
        run: exit 1

