name: test-nn-ivy
on:
  push:
  pull_request:
    types: [labeled, review_requested]
permissions:
  actions: read
jobs:
   run-nightly-tests:
     strategy:
       matrix:
         backends :  [numpy, torch, jax, tensorflow]
         submodules: [test_activations, test_layers, test_losses, test_norms]
     continue-on-error: true
     runs-on: ubuntu-latest
     steps:
       - name: Checkout 🛎️Ivy
         uses: actions/checkout@v2
         with:
           path: ivy
           persist-credentials: false
           submodules: "recursive"

#       - name: Download artifact
#         uses: dawidd6/action-download-artifact@v2
#         with:
#           workflow: test-ivy-nn.yml
#           workflow_conclusion: completed
#           name: hypothesis_${{ matrix.backends }}_${{ matrix.submodules }}_zip
#           path: |
#             ivy/.hypothesis/
#
#       - name: Unzip Hypothesis Examples
#         run: |
#           cd ivy/.hypothesis
#           unzip examples.zip
#           rm examples.zip

       - name: Run Functional-NN Tests
         id: tests
         run: |
           cd ivy
           mkdir -p .hypothesis
           cd .hypothesis
           mkdir -p examples
           cd ..
           ./test_ivy_nn.sh ${{ matrix.backends }} ${{ matrix.submodules }}

       - name: Zip Hypothesis Examples
         run: |
           cd ivy/.hypothesis
           zip -r examples.zip examples

       - name: Upload hypothesis
         uses: actions/upload-artifact@v3
         with:
           name: hypothesis_${{ matrix.backends }}_${{ matrix.submodules }}_zip
           path: |
             ivy/.hypothesis/examples.zip

#      - name: Check on failures
#        if: steps.tests.outcome != 'success'
#        run: exit 1