name: intelligent-tests-temp
on:
  workflow_dispatch:
permissions:
  actions: read
jobs:
   run_tests_1:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout Ivy 🛎
         uses: actions/checkout@v2
         with:
           path: ivy
           persist-credentials: false
           submodules: "recursive"
           fetch-depth: 100

       - name: Update Mapping and Determine Tests
         env:
           SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
         run: |
           source ./ivy/push_mapping.sh master
           pip install pydriller pymongo
           cp Mapping/tests.pbz2 ivy/
           cd Mapping
           echo "Test" > tests.pbz2
           git add .
           git commit -m "Update Mapping Test"
           git push origin master
         continue-on-error: true

       - name: Run Tests
         id: tests
         env:
           SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
         run: |
           cd ivy
           python run_tests.py ${{ secrets.REDIS_CONNECTION_URL }} ${{ secrets.REDIS_PASSWORD }} ${{ secrets.MONGODB_PASSWORD }} ${{ steps.jobs.outputs.html_url }}
         continue-on-error: true

       - name: Check on failures
         if: steps.tests.outcome != 'success'
         run: exit 1
