name: intelligent-tests-temp
on:
  workflow_dispatch:
permissions:
  actions: read
jobs:
   run_tests_1:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout Ivy 🛎
         uses: actions/checkout@v2
         with:
           path: ivy
           persist-credentials: false
           submodules: "recursive"
           fetch-depth: 100

       - name: Determine and Run Tests
         id: tests
         run: |
           ./ivy/push_mapping.sh ${{ secrets.SSH_DEPLOY_KEY }}
           cd Mapping
           echo "Hello!" > tests.pbz2
           git push origin master
         continue-on-error: true
