name: test-frontend-torch-push
on: push
permissions:
  actions: read
jobs:
  run-nightly-tests:
    strategy:
      matrix:
        backends: [numpy, torch, jax, tensorflow ]
        submodules: [blas_and_lapack_ops, comparison_ops, convolution_functions, creation_ops,
                    distance_functions, dropout_functions, indexing_slicing_joining_mutating_ops,
                    linear_functions, locally_disabling_gradient_computation, loss_functions, miscellaneous_ops,
                    non_linear_activation_functions, pointwise_ops, pooling_functions, random_sampling, reduction_ops,
                    sparse_functions, spectral_ops, tensor, tensor_functions, utilities, vision_functions]
    continue-on-error: true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️Ivy
        uses: actions/checkout@v2
        with:
          path: ivy
          persist-credentials: false
          submodules: "recursive"

      - name: Check Files Changed
        shell: pwsh
        id: check_file_changed
        run: |
          cd ivy
          $diff = git diff --name-only HEAD^ HEAD
          $SourceDiff = $diff | Where-Object { `
              $_ -match 'ivy_tests/test_ivy/test_frontends/test_torch/test_${{ matrix.submodules }}.py' `
          }
          $HasDiff = $SourceDiff.Length -gt 0
          Write-Host "::set-output name=changed::$HasDiff"

      - name: Run Frontend Tests
        if: steps.check_file_changed.outputs.changed == 'True'
        id: tests
        run: |
          cd ivy
          ./run_tests_CLI/test_torch_frontend.sh ${{ matrix.backends }} test_${{ matrix.submodules }} ${{ secrets.REDIS_CONNECTION_URL }} ${{ secrets.REDIS_PASSWORD}}
        continue-on-error: true

      - name: Install Mongo Python Client
        if: steps.check_file_changed.outputs.changed == 'True'
        uses: BSFishy/pip-action@v1
        with:
            packages: |
              pymongo[srv]

      - name: Update Database
        if: steps.check_file_changed.outputs.changed == 'True'
        env:
            MONGODB_PASSWORD: ${{ secrets.MONGODB_PASSWORD }}
        run: |
            cd ivy/automation_tools/dashboard_automation/
            python3 update_db.py "$MONGODB_PASSWORD" ${{ github.workflow }} "${{ matrix.backends }}-${{ matrix.submodules }}" ${{ steps.tests.outcome }} ${{ github.run_id }}
        continue-on-error: true

      - name: Check on failures
        if: steps.check_file_changed.outputs.changed == 'True' && steps.tests.outcome != 'success'
        run: exit 1
