name: test-array-api-torch
on:
  push:
  pull_request:
    types: [labeled, opened, reopened, edited]
  workflow_dispatch:

jobs:
  run-torch-array-api-tests:
    if: ${{ github.event.label.name!='Function Reformatting' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️Ivy
        uses: actions/checkout@v2
        with:
          path: ivy
          persist-credentials: false
          submodules: 'recursive'

      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: test-array-api-torch.yml
          workflow_conclusion: success
          name: hypothesis
          path: |
            ivy/.hypothesis

      - name: Run Torch Tests
        id: tests
        run: |
          cd ivy
          ./test_array_api.sh torch
        continue-on-error: true
        
      - name: Upload hypothesis
        uses: actions/upload-artifact@v3
        with:
          name: hypothesis
          path: |
            ivy/.hypothesis
    
      - name: Check on failures
        if: steps.tests.outcome != 'success'
        run: exit 1
