name: test-core-ivy
on:
  push:
  pull_request:
    types: [labeled, review_requested]
permissions:
  actions: read
jobs:
   run-nightly-tests:
     strategy:
       matrix:
         backends :  [numpy, torch, jax, tensorflow]
         submodules: [test_creation, test_device, test_dtype, test_elementwise, test_general, test_gradients, test_linalg,
                     test_manipulation, test_meta, test_nest, test_random, test_searching, test_set, test_sorting, test_statistical,
                     test_utility]
     continue-on-error: true
     runs-on: ubuntu-latest
     steps:
       - name: Checkout 🛎️Ivy
         uses: actions/checkout@v2
         with:
           path: ivy
           persist-credentials: false
           submodules: "recursive"

       - name: Cache hypothesis
         uses: actions/cache@v3
         with:
           path: |
             ivy/.hypothesis
           key: ${{ runner.os }}-hypothesis

       - name: Run Functional-Core Tests
         id: tests
         run: |
           cd ivy
           mkdir -p .hypothesis
           ./test_ivy_core.sh ${{ matrix.backends }} ${{ matrix.submodules }}
