name: test-ivy
on:
  push:
  pull_request:
    types : [labeled, opened, reopened, edited]
jobs:
  run-nightly-tests:
    if: ${{ github.event.label.name!='Function Reformatting' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️Ivy
        uses: actions/checkout@v2
        with:
          path: ivy
          persist-credentials: false
          submodules: 'recursive'

      - name: Cache hypothesis
        uses: actions/cache@v3
        with:
          path: |
            ivy/.hypothesis
          key: ${{ runner.os }}-hypothesis

      - name: Run Tests
        run: |
          cd ivy
          mkdir -p .hypothesis
          docker run --rm -v `pwd`:/ivy -v `pwd`/.hypothesis:/.hypothesis unifyai/ivy:latest python3 -m pytest ivy/ivy_tests/test_ivy
