name: test-core-ivy-manual
on:
  workflow_dispatch:

permissions:
  actions: read
jobs:
   run-nightly-tests:
     strategy:
       matrix:
         backends :  [numpy, torch, jax, tensorflow]
         submodules: [test_creation, test_device, test_dtype, test_elementwise, test_general, test_gradients, test_linalg,
                     test_manipulation, test_meta, test_nest, test_random, test_searching, test_set, test_sorting, test_statistical,
                     test_utility]
     continue-on-error: true
     runs-on: ubuntu-latest
     steps:
       - name: Checkout 🛎️Ivy
         uses: actions/checkout@v2
         with:
           path: ivy
           persist-credentials: false
           submodules: "recursive"

       - name: Download artifact
         uses: dawidd6/action-download-artifact@v2
         with:
           github_token: ${{secrets.GITHUB_TOKEN}}
           workflow: test-ivy-core-manual.yml
           workflow_conclusion: completed
           name: hypothesis_${{ matrix.backends }}_${{ matrix.submodules }}_zip
           path: |
             ivy/.hypothesis/
         continue-on-error: true

       - name: Unzip Hypothesis Examples
         id: unzip
         run: |
           cd ivy/.hypothesis
           unzip examples.zip
           rm examples.zip
         continue-on-error: true

       - name: Create Hypothesis Directory
         if: steps.unzip.outcome != 'success'
         run: |
           cd ivy
           mkdir -p .hypothesis
           cd .hypothesis
           mkdir -p examples
         continue-on-error: true

       - name: Run Functional-Core Tests
         id: tests
         run: |
           cd ivy
           ./run_tests_CLI/test_ivy_core.sh ${{ matrix.backends }} ${{ matrix.submodules }}
         continue-on-error: true

       - name: Zip Hypothesis Examples
         run: |
           cd ivy/.hypothesis
           zip -r examples.zip examples
         continue-on-error: true

       - name: Upload hypothesis
         uses: actions/upload-artifact@v3
         with:
           name: hypothesis_${{ matrix.backends }}_${{ matrix.submodules }}_zip
           path: |
             ivy/.hypothesis/examples.zip
         continue-on-error: true

       - name: Check on failures
         if: steps.tests.outcome != 'success'
         run: exit 1