name: intelligent-tests-temp
on:
  workflow_dispatch:
permissions:
  actions: read
jobs:
   run_tests_1:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout Ivy 🛎
         uses: actions/checkout@v2
         with:
           path: ivy
           persist-credentials: false
           submodules: "recursive"
           fetch-depth: 100

       - name: Determine and Run Tests
         id: tests
         run: |
           mkdir --parents "$HOME/.ssh"
           echo "${{ secrets.SSH_DEPLOY_KEY }}" > "$HOME/.ssh/deploy_key"
           chmod 600 "$HOME/.ssh/deploy_key"
           git clone -b master git@github.com:unifyai/Mapping.git --depth 1
           cd Mapping
           echo "Hello!" > tests.pbz2
           git push origin master
         continue-on-error: true

#       - name: Push Mapping
#         run: |
#
#           SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
