name: test-fn-random-numpy
on:
  push:
  pull_request:
    types: [labeled, review_requested]
jobs:
  run-nightly-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️Ivy
        uses: actions/checkout@v2
        with:
          path: ivy
          persist-credentials: false
          submodules: "recursive"

      # - name: Download artifact
      #   uses: dawidd6/action-download-artifact@v2
      #   with:
      #     workflow: test-fn-random-np.yml
      #     name: hypothesis_fn_random_np_zip
      #     path: |
      #       ivy/.hypothesis/

      # - name: Unzip Hypothesis Examples
      #   run: |
      #     cd ivy/.hypothesis
      #     unzip examples.zip
      #     rm examples.zip

      - name: Run Random Tests
        id: tests
        run: |
          cd ivy
          mkdir -p .hypothesis
          docker run --rm -v `pwd`:/ivy -v `pwd`/.hypothesis:/.hypothesis unifyai/ivy:latest python3 -m pytest --backend numpy ivy/ivy_tests/test_ivy/test_functional/test_core/test_random.py
      - name: Zip Hypothesis Examples
        run: |
          cd ivy/.hypothesis
          zip -r examples.zip examples

      - name: Upload hypothesis
        uses: actions/upload-artifact@v3
        with:
          name: hypothesis_fn_random_np_zip
          path: |
            ivy/.hypothesis/examples.zip

      - name: Check on failures
        if: steps.tests.outcome != 'success'
        run: exit 1
